<!DOCTYPE HTML>
<html>
	<head>
		<link rel="stylesheet" href="/public/bundles/bootstrap/css/bootstrap.min.css"/>
		<link rel="stylesheet" href="/public/bundles/fontawesome/css/fontawesome.min.css"/>
		<link rel="stylesheet" href="/public/res/css/main-style.css"/>
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<?= $this->yieldView(); ?>
				</div>
			</div>
		</div>
		<script src="/public/res/js/jquery.min.js"></script>
		<script src="/public/bundles/bootstrap/js/bootstrap.min.js"></script>
		<script src="/public/bundles/fontawesome/js/fontawesome.min.js"></script>
	</body>	
</html>