<html>
	<head>
		<link rel="stylesheet" href="/public/bundles/bootstrap/css/bootstrap.min.css"/>
	</head>
	<body>
		<div class="container">
			<pre>Welcome from main layout!</pre>
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<?= $this->yieldView(); ?>
				</div>
			</div>
		</div>
	</body>
	<link rel="stylesheet" href="/public/bundles/bootstrap/js/bootstrap.min.js"/>
</html>